// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebsiteTester.Persistenсe;

#nullable disable

namespace WebsiteTester.Persistenсe.Migrations
{
    [DbContext(typeof(WebsiteTesterDbContext))]
    partial class WebsiteTesterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("WebsiteTester.Domain.Models.LinkTestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInSitemap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInWebsite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RenderTimeMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TestedLinkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestedLinkId");

                    b.ToTable("LinkTestResult");
                });

            modelBuilder.Entity("WebsiteTester.Domain.Models.TestedLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestedLink");
                });

            modelBuilder.Entity("WebsiteTester.Domain.Models.LinkTestResult", b =>
                {
                    b.HasOne("WebsiteTester.Domain.Models.TestedLink", "TestedLink")
                        .WithMany("Links")
                        .HasForeignKey("TestedLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestedLink");
                });

            modelBuilder.Entity("WebsiteTester.Domain.Models.TestedLink", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
